apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  labels:
    control-plane: controller-manager
    app: fdb-kubernetes-operator-controller-manager
spec:
  selector:
    matchLabels:
      app: fdb-kubernetes-operator-controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
        app: fdb-kubernetes-operator-controller-manager
    spec:
      containers:
      - command:
        - /manager
        image: controller:latest
        imagePullPolicy: IfNotPresent
        name: manager
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 500m
            memory: 128Mi
      terminationGracePeriodSeconds: 10