name: CI for master branch

on:
  push:
    branches: master

jobs:
  push_images:
    name: Push Docker images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - fdb-kubernetes-operator
          - fdb-data-loader
        include:
          - image: fdb-kubernetes-operator
            context: ./
            name: foundationdb/fdb-kubernetes-operator
          - image: fdb-data-loader
            context: ./sample-apps/data-loader
            name: foundationdb/fdb-data-loader
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ matrix.context }}
          tags: ${{ matrix.name }}:latest
