operator:
  name: fdb-kubernetes-operator-controller-manager
  image: foundationdb/fdb-kubernetes-operator
  tag: 0.24.0
  role: fdb-kubernetes-operator-manager-role
  rolebinding: fdb-kubernetes-operator-manager-rolebinding
