operator:
  name: fdb-kubernetes-operator-controller-manager
  image: foundationdb/fdb-kubernetes-operator
  tag: v0.29.0
  role: fdb-kubernetes-operator-manager-role
  rolebinding: fdb-kubernetes-operator-manager-rolebinding
  globalMode:
    enabled: false
  replicas: 1

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 500m
    memory: 256Mi
